// <auto-generated />
using Leantavla.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leantavla.Server.Migrations
{
    [DbContext(typeof(LeantavlaContext))]
    [Migration("20210205224012_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Leantavla.Shared.Lapp", b =>
                {
                    b.Property<int>("LappId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sammanfattning")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LappId");

                    b.ToTable("Lappar");
                });
#pragma warning restore 612, 618
        }
    }
}
